version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir : '/pythonfile'
    tty : true
    volumes:
      -./pythonfile:/pythonfile/

# docker run -d pythonfile